### ISSUE TITLE
Handle saving multiple files enclosed in ``` to generate an app

### ISSUE THREAD

**Issue by drorm** [drorm/gish#10]
GPT4 is capable of generating full solutions that include multiple files enclosed in the conventional format of triple backticks. In general, it seems to have the inclination to include these even when not asked to.

You can ask it to generate a file like this (because of the markdown in the file, can't include it inline):
[example.txt](https://github.com/drorm/gish/files/11144730/example.txt)

So in effect, we could, with a simple gish request, generate a full, multi-file application, or library.
Generate the files in a directory, and for extra points, we can launch a local server, and the app is right there in the user's browser :-).

**Comment by syonfox** [comment]
This will be a common trend as new versions are trained on data from chat.openai.com and people are asking for formated output so they can paste it. Most likely we want to incorporate an md parser. as an optional display layer. I think it's possible to fine-tune a model for md on and md off but not cost effective in the current api landscape.

**Comment by drorm** [comment]
I'm inclined not to have the output as an md file, but rather use the prompt to tell GPT to only provide us files enclosed in ```.
On further thought, I created #12 as a first step, specific to web application, and can generalize later for others like node.js, etc.

**Comment by drorm** [comment]
This is pretty much done in the just released V0.3. 
See the nodejs [word count example](https://github.com/drorm/gish/blob/main/examples/nodeapp.txt).
The prompt has a bit of an issue since GPT often references old packages, but this can probably be solved with a bit of work around telling it to use "*" for the package or some combination of npm upgrade and npm update.
