### ISSUE TITLE
Gish seems to have dropped a space character in the first prompt I tried?

### ISSUE THREAD

**Issue by paul-gauthier** [drorm/gish#9]
Notice the lack of space between `approximately12,742`.

The same "how big is the earth" returns the same text from the api, except with the expected space. So it seems like maybe there's some text parsing issue in gish?

```
$ gish how big is the earth | cat
The Earth has a diameter of approximately12,742 kilometers (7,918 miles) and a circumference of about 40,075 kilometers (24,901 miles).
Tokens: 39 Cost: $0.000078 Elapsed: 1.422 Seconds. Tokens and cost are estimates when streaming.
```

**Comment by drorm** [comment]
Confirmed, I can reproduce it. 
It's an issue with the streaming response. If you do --no-stream it's not there.
I'll analyze some more and look for a fix.

**Comment by drorm** [comment]
Got a fix, deploying a new release to fix this.

**Comment by drorm** [comment]
V0.2.1 has been deployed with a fix for this.
